
version: "3.9" 

services:

  api:
    container_name: nest_api
    build: .
    ports:
        - ${API_PORT}:${API_PORT}
    volumes:
       - .:/home/api
       - /home/api/node_modules
    environment:
      DB_HOST: database

  database:
    container_name: nest_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  